version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    
    # Ignore AWS SDK updates & X-Ray SDK updates - to be done manually
    ignore:
      - dependency-name: "com.amazonaws:*"  
      - dependency-name: "software.amazon.awssdk:*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
